const scroll = new LocomotiveScroll({
  el: document.querySelector("#main"),
  smooth: true,
});

gsap.from(".navLink", {
  y: 15,
  opacity: 0,
  duration: 1,
  stagger: 0.2,
  ease: "power3.out",
});

Shery.textAnimate("#heading h1", {
  style: 2,
  y: 10,
  delay: 0.3,
  duration: 1.5,
  ease: "cubic-bezier(0.23, 1, 0.320, 1)",
});

gsap.from(".animation", {
  y: 30,
  opacity: 0,
  duration: 1,
  stagger: 0.2,
  ease: "power1.out",
});

Shery.imageEffect(".imgntext img", {
  style: 3,
  config: {
    uFrequencyX: { value: 16.03, range: [0, 100] },
    uFrequencyY: { value: 15.27, range: [0, 100] },
    uFrequencyZ: { value: 17.56, range: [0, 100] },
    geoVertex: { range: [1, 64], value: 20.24 },
    zindex: { value: "-9996999", range: [-9999999, 9999999] },
    aspect: { value: 0.7500108994201509 },
    ignoreShapeAspect: { value: true },
    shapePosition: { value: { x: 0, y: 0 } },
    shapeScale: { value: { x: 0.5, y: 0.5 } },
    shapeEdgeSoftness: { value: 0.37, range: [0, 0.5] },
    shapeRadius: { value: 0, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: false },
    infiniteGooey: { value: false },
    growSize: { value: 4, range: [1, 15] },
    durationOut: { value: 1, range: [0.1, 5] },
    durationIn: { value: 1.5, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.4, range: [1, 5] },
    scrollType: { value: 0 },
    noEffectGooey: { value: true },
    onMouse: { value: 1 },
    noise_speed: { value: 0.2, range: [0, 10] },
    metaball: { value: 0.2, range: [0, 2] },
    discard_threshold: { value: 0.5, range: [0, 1] },
    antialias_threshold: { value: 0.002, range: [0, 0.1] },
    noise_height: { value: 0.5, range: [0, 2] },
    noise_scale: { value: 10, range: [0, 100] },
  },
  debug: false,
});

Shery.imageEffect("#sus_Image img", {
  style: 5,
  config: {
    a: { value: 2.75, range: [0, 30] },
    b: { value: 0.75, range: [-1, 1] },
    zindex: { value: -9996999, range: [-9999999, 9999999] },
    aspect: { value: 0.6562563580874873 },
    ignoreShapeAspect: { value: true },
    shapePosition: { value: { x: 0, y: 0 } },
    shapeScale: { value: { x: 0.5, y: 0.5 } },
    shapeEdgeSoftness: { value: 0, range: [0, 0.5] },
    shapeRadius: { value: 0, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: false },
    infiniteGooey: { value: false },
    growSize: { value: 4, range: [1, 15] },
    durationOut: { value: 1, range: [0.1, 5] },
    durationIn: { value: 1.5, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.58, range: [1, 5] },
    scrollType: { value: 0 },
    geoVertex: { range: [1, 64], value: 1 },
    noEffectGooey: { value: true },
    onMouse: { value: 0 },
    noise_speed: { value: 0.2, range: [0, 10] },
    metaball: { value: 0.2, range: [0, 2] },
    discard_threshold: { value: 0.5, range: [0, 1] },
    antialias_threshold: { value: 0.002, range: [0, 0.1] },
    noise_height: { value: 0.5, range: [0, 2] },
    noise_scale: { value: 10, range: [0, 100] },
  },
  debug: false,
});

gsap.from(".imgntext img", {
  z: -40,
  opacity: 0,
  ease: "power1.out",
  duration: 1,
});

gsap.from("#sus_Image img", {
  z: 10,
  opacity: 0,
  ease: "power1.out",
  duration: 1,
});

Shery.imageEffect("#leftImg .img1", {
  style: 2,
  config: {
    resolutionXY: { value: 100 },
    distortion: { value: true },
    mode: { value: -8 },
    mousemove: { value: 2 },
    modeA: { value: 0 },
    modeN: { value: 0 },
    speed: { value: 1, range: [-500, 500], rangep: [-10, 10] },
    frequency: { value: 50, range: [-800, 800], rangep: [-50, 50] },
    angle: { value: 0.5, range: [0, 3.141592653589793] },
    waveFactor: { value: 1.4, range: [-3, 3] },
    color: { value: 10212607 },
    pixelStrength: { value: 3, range: [-20, 100], rangep: [-20, 20] },
    quality: { value: 5, range: [0, 10] },
    contrast: { value: 1, range: [-25, 25] },
    brightness: { value: 1, range: [-1, 25] },
    colorExposer: { value: 0.18, range: [-5, 5] },
    strength: { value: 0.2, range: [-40, 40], rangep: [-5, 5] },
    exposer: { value: 8, range: [-100, 100] },
    zindex: { value: -9996999, range: [-9999999, 9999999] },
    aspect: { value: 2.666696808029659 },
    ignoreShapeAspect: { value: true },
    shapePosition: { value: { x: -0.08, y: 0 } },
    shapeScale: { value: { x: 0.62, y: 0.5 } },
    shapeEdgeSoftness: { value: 0.02, range: [0, 0.5] },
    shapeRadius: { value: 0.2, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: false },
    infiniteGooey: { value: false },
    growSize: { value: 4, range: [1, 15] },
    durationOut: { value: 1, range: [0.1, 5] },
    durationIn: { value: 1.5, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.67, range: [1, 5] },
    scrollType: { value: 1 },
    geoVertex: { range: [1, 64], value: 1 },
    noEffectGooey: { value: true },
    onMouse: { value: 1 },
    noise_speed: { value: 0.2, range: [0, 10] },
    metaball: { value: 0.2, range: [0, 2] },
    discard_threshold: { value: 0.5, range: [0, 1] },
    antialias_threshold: { value: 0.002, range: [0, 0.1] },
    noise_height: { value: 0.5, range: [0, 2] },
    noise_scale: { value: 10, range: [0, 100] },
  },
});

Shery.imageEffect("#rightImg .img2", {
  style: 2,
  config: {
    resolutionXY: { value: 100 },
    distortion: { value: true },
    mode: { value: 7 },
    mousemove: { value: 2 },
    modeA: { value: 0 },
    modeN: { value: 1 },
    speed: { value: 1, range: [-500, 500], rangep: [-10, 10] },
    frequency: { value: 50, range: [-800, 800], rangep: [-50, 50] },
    angle: { value: 0.5, range: [0, 3.141592653589793] },
    waveFactor: { value: 1.4, range: [-3, 3] },
    color: { value: 10212607 },
    pixelStrength: { value: 3, range: [-20, 100], rangep: [-20, 20] },
    quality: { value: 5, range: [0, 10] },
    contrast: { value: 1, range: [-25, 25] },
    brightness: { value: 1, range: [-1, 25] },
    colorExposer: { value: 0.18, range: [-5, 5] },
    strength: { value: 0.2, range: [-40, 40], rangep: [-5, 5] },
    exposer: { value: 8, range: [-100, 100] },
    zindex: { value: -9996999, range: [-9999999, 9999999] },
    aspect: { value: 2.8889140066913828 },
    ignoreShapeAspect: { value: true },
    shapePosition: { value: { x: 0.29, y: 0 } },
    shapeScale: { value: { x: 0.92, y: 0.5 } },
    shapeEdgeSoftness: { value: 0.04, range: [0, 0.5] },
    shapeRadius: { value: 0.18, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: false },
    infiniteGooey: { value: false },
    growSize: { value: 4, range: [1, 15] },
    durationOut: { value: 1, range: [0.1, 5] },
    durationIn: { value: 1.5, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.09, range: [1, 5] },
    scrollType: { value: 1 },
    geoVertex: { range: [1, 64], value: 1 },
    noEffectGooey: { value: true },
    onMouse: { value: 1 },
    noise_speed: { value: 0.2, range: [0, 10] },
    metaball: { value: 0.2, range: [0, 2] },
    discard_threshold: { value: 0.5, range: [0, 1] },
    antialias_threshold: { value: 0.002, range: [0, 0.1] },
    noise_height: { value: 0.5, range: [0, 2] },
    noise_scale: { value: 10, range: [0, 100] },
  },
});

Shery.imageEffect("#pckgImg", {
  style: 6,
  config: {
    noiseDetail: { value: 9.92, range: [0, 100] },
    distortionAmount: { value: 1.15, range: [0, 10] },
    scale: { value: 29.01, range: [0, 100] },
    speed: { value: 0.63, range: [0, 1] },
    zindex: { value: -9996999, range: [-9999999, 9999999] },
    aspect: { value: 1.75 },
    ignoreShapeAspect: { value: true },
    shapePosition: { value: { x: 0, y: 0 } },
    shapeScale: { value: { x: 0.5, y: 0.5 } },
    shapeEdgeSoftness: { value: 0, range: [0, 0.5] },
    shapeRadius: { value: 0, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: true },
    infiniteGooey: { value: true },
    growSize: { value: 3.89, range: [1, 15] },
    durationOut: { value: 2.49, range: [0.1, 5] },
    durationIn: { value: 1.82, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.21, range: [1, 5] },
    scrollType: { value: 0 },
    geoVertex: { range: [1, 64], value: 1 },
    noEffectGooey: { value: true },
    onMouse: { value: 0 },
    noise_speed: { value: 0.53, range: [0, 10] },
    metaball: { value: 0.2, range: [0, 2], _gsap: { id: 34 } },
    discard_threshold: { value: 0.74, range: [0, 1] },
    antialias_threshold: { value: 0.1, range: [0, 0.1] },
    noise_height: { value: 0.4, range: [0, 2] },
    noise_scale: { value: 12.21, range: [0, 100] },
  },
  gooey:true
});

document.querySelector("#textnBtn button").addEventListener("mouseover", () =>{
  gsap.to("#future video", {
    opacity: 1,
    duration:1,
    ease:"power1.out"
  })
});

document.querySelector("#textnBtn button").addEventListener("mouseleave", () =>{
  gsap.to("#future video", {
    opacity: 0,
    duration:1,
    ease:"power1.out"
  })
});